### ISSUE TITLE
2021-09-27 08:01:06 E/main: Exception in coroutine <unnamed>

### ISSUE THREAD

**Issue by scienceshell** [StageGuard/SuperCourseTimetableBot#23]
java.lang.IndexOutOfBoundsException: Index 11 out of bounds for length 10
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
        at java.base/java.util.Objects.checkIndex(Objects.java:359)
        at java.base/java.util.ArrayList.get(ArrayList.java:427)
        at me.stageguard.sctimetable.service.messageRoute.QueryCourseKt$queryCourse$2$1.invoke(queryCourse.kt:69)
        at me.stageguard.sctimetable.service.messageRoute.QueryCourseKt$queryCourse$2$1.invoke(queryCourse.kt:63)
        at kotlin.text.StringsKt__AppendableKt.appendElement(Appendable.kt:85)
        at kotlin.collections.CollectionsKt___CollectionsKt.joinTo(_Collections.kt:3344)
        at kotlin.collections.CollectionsKt___CollectionsKt.joinToString(_Collections.kt:3361)
        at kotlin.collections.CollectionsKt___CollectionsKt.joinToString$default(_Collections.kt:3360)
        at me.stageguard.sctimetable.service.messageRoute.QueryCourseKt$queryCourse$2.invokeSuspend(queryCourse.kt:63)
        at me.stageguard.sctimetable.service.messageRoute.QueryCourseKt$queryCourse$2.invoke(queryCourse.kt)
        at me.stageguard.sctimetable.service.messageRoute.QueryCourseKt$queryCourse$2.invoke(queryCourse.kt)
        at me.stageguard.sctimetable.database.Database$suspendQuery$3.invokeSuspend(Database.kt:49)
        at me.stageguard.sctimetable.database.Database$suspendQuery$3.invoke(Database.kt)
        at me.stageguard.sctimetable.database.Database$suspendQuery$3.invoke(Database.kt)
        at org.jetbrains.exposed.sql.transactions.experimental.SuspendedKt$suspendedTransactionAsyncInternal$1.invokeSuspend(Suspended.kt:116)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
貌似是从昨天开始的，昨天我先发明天课程就不回复我了，但现在课程提醒功能没有事情，Java是16用的centOS7

**Comment by StageGuard** [comment]
时间表没有最后几节的课程，比如这一天有12节课，但是时间表只有10节课的信息
